apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-serverless-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BenedictusAryo/cluster-serverless.git
    targetRevision: main
    path: infra
    helm:
      releaseName: cluster-serverless-infra
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    # Ignore operator-managed status fields
    - group: operator.knative.dev
      kind: KnativeServing
      jsonPointers:
        - /status
    - group: operator.knative.dev
      kind: KnativeEventing
      jsonPointers:
        - /status
