# Enable the infra-apps subchart for app of apps pattern
infra-apps:
  enabled: true

# ArgoCD HTTPRoute configuration
argocd:
  httproute:
    enabled: true
    hostname: argocd.benedict-aryo.com

# Configuration for different cluster components
cilium:
  enabled: true

certificateManager:
  enabled: true
  email: "admin@benedict-aryo.com"  # Replace with your email
  cloudflare:
    email: "admin@benedict-aryo.com"  # Replace with your Cloudflare email

cloudflareTunnel:
  enabled: true
  tunnelId: "0ce50236-7a62-4a88-9bed-a0e1b60d0e81"
  namespace: "default"
  useConfigFile: false
  ingress: []

sealedSecrets:
  enabled: true

istio:
  enabled: true

knative:
  enabled: true
