{{- if .Values.applications }}
{{- range .Values.applications }}
{{- if (or (not (hasKey . "active")) .active) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "argocd" }}
  annotations:
    # Track the application status in the parent cluster-init chart
    argocd.argoproj.io/tracking-id: cluster-init:argoproj.io/Application:{{ .namespace | default "argocd" }}/{{ .name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .repoURL | quote }}
    {{- if .chart }}
    chart: {{ .chart | quote }}
    targetRevision: {{ .version | default .targetRevision | quote }}
    {{- else }}
    targetRevision: {{ .targetRevision | quote }}
    {{- if .path }}
    path: {{ .path | quote }}
    {{- end }}
    {{- if .valueFiles }}
    helm:
      releaseName: {{ .name }}
      valueFiles:
        {{- range .valueFiles }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .destinationNamespace | default .namespace | default "argocd" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
{{- end }}
{{- end }}
